//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theSeed39Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("theSeed39Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   골드비치 리조트에 거주하는 잡화 상인 이름은? | 스크루지 | 나탈리 | 메이슨 | 베티 | 3
        ///노틸러스의 무기 상인 이름은? | 리드 | 프란시스 | 테스 | 모건 | 4
        ///노틸러스의 잡화 상인 이름은? | 잭 | 시나몬 | 미르 | 갤리 | 4
        ///노틸러스의 창고지기 이름은? | 슈리츠 | 다고쓰 | 론도 | 돈틀레스 | 4
        ///누구의 대사일까? - 고대 노바의 신을 모시고 있습니다. | 소피아 | 브로커 정 | 펜릴 | 론도 | 3
        ///누구의 대사일까? - 나의 근육을 보라구. 나처럼 강해지고 싶지 않나? | 지미 | 뮤네 | 쿤 | 테스 | 3
        ///누구의 대사일까? - 난 앞치마가 잘 어울리는 남자야. | 헬레나 | 일렉스 | 크루소 | 프레드릭 | 2
        ///누구의 대사일까? - 날씨가 참 좋죠? 해피와 산책하기 좋은 날씨입니다. | 큐트 | 게렉터 | 시나몬 | 알렉스 | 2
        ///누구의 대사일까? - 내가 주워왔으니까 내가 책임져! | 비어완 | 프레드릭 | 골드리치 | 랑 | 4
        ///누구의 대사일까? - [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quizGang {
            get {
                object obj = ResourceManager.GetObject("quizGang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
